### ISSUE TITLE
Code for the test cases

### ISSUE THREAD

**Issue by RENEEGAILP** [briansp8210/sdb#1]
Could you commit the code as well as build command for your tests guess and hello64?
I am trying to run your debugger on similar helloworld file but on command start it doesn't stop at the first instruction but continues execution directly.

**Comment by briansp8210** [comment]
Hi, those test files are provided by the course, I don't have the source code.
I try to write and build a simple helloworld and it works as expected.

```c
// gcc hello.c -o hello
#include <stdio.h>

int main(void) {
  printf("Hello, world!\n");
  return 0;
}
```

Could you provide more details of your environment?

**Comment by RENEEGAILP** [comment]
![sdbtest](https://user-images.githubusercontent.com/22723224/127199446-2866ffd2-8ed5-476b-b66b-b57512729069.PNG)

I have attached the steps that I have used. hello is the program that I compiled and hello64 is provided in tests.
I have used the code provided in the previous comment

I am running this code on a Ubuntu machine in a VirtualBox environment. Let me know if you need any additional details

**Comment by briansp8210** [comment]
What is your Ubuntu release?
Also the kernel and gcc version might be helpful.
Thanks.

**Comment by RENEEGAILP** [comment]
My Ubuntu release is 20.04
GCC version is 9.3.0
Kernel version is 5.8.0-63-generic

I am going to try this on Ubuntu 18.04 as mentioned in the usage guide since I think it works on that release of Ubuntu. I'll post an update once I try that.

**Comment by RENEEGAILP** [comment]
I reproduced the same case on Ubuntu 18.04 and it works as expected. I am not sure why there is an issue with 20.04 release. Thanks for the help!
